export default function NavbarButton({ children, onClick, className = "" }) {
    return (
        <button
            onClick={onClick}
            className={`
                group
                relative
                w-full
                rounded-xl
                bg-transparent
                border-none
                text-black
                cursor-pointer
                px-3
                py-2
                text-left
                transition-colors
                duration-200
                hover:text-black
                focus:outline-none
                focus:text-black
                font-semibold
                md:w-auto
                md:rounded-none
                md:px-1
                md:py-1
                md:text-center
                ${className}
            `}
            style={{ fontFamily: '"Helvetica Neue", Arial, sans-serif' }}
        >
            <span className="relative flex w-full flex-col items-start md:items-center">
                {children}
                <span
                    className="
                        absolute
                        left-0
                        md:left-1/2
                        md:-translate-x-1/2
                        bottom-[-8px]
                        h-1
                        w-full
                        scale-x-0
                        rounded-full
                        bg-gradient-to-r
                        from-orange-400
                        to-red-700
                        transition-transform
                        duration-300
                        ease-out
                        origin-left
                        md:origin-center
                        group-hover:scale-x-100
                    "
                />
            </span>
        </button>
    );
}
